# -*- coding: utf-8 -*-
"""streamlitv2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HXS5c0pEyIvaxjZB0vRxMo8zVv1kGISh
"""

! pip install streamlit
! pip install streamlit-folium

import folium
import streamlit as st

import streamlit as st
import folium

map = folium.Map(location=[-25.441105, -49.276855], zoom_start=12)

st.write(map)